version: "3"

services:
  vote:
    build: ./vote
    command: 
    - python 
    - app.py
    ports:
      - "5000:80"
    depends_on:
      - "redis"
      - "db"

  result:
    image: node:latest

  worker:
    build:
      context: ./worker
    ports:
      - "5002:8080"
    depends_on:
      - "redis"
      - "db"

  redis:
    image: redis:alpine

  db:
    image: postgres:latest
